version: '3.8'

services:
  server:
    build:
      context: ./backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    networks:
      - terminal-share

  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
    environment:
      - NEXT_PUBLIC_SOCKET_URL=http://server:3001
    networks:
      - terminal-share

networks:
  terminal-share:
    driver: bridge
